# Generated by Django 3.2.8 on 2022-08-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='user_default', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
